steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/PROJECT_ID/my-docker-repo/my-image:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/PROJECT_ID/my-docker-repo/my-image:$COMMIT_SHA']
images:
  - 'asia-southeast1-docker.pkg.dev/PROJECT_ID/my-docker-repo/my-image:$COMMIT_SHA'
